spring:
  datasource:
    generate-unique-name: false

  h2:
    console:
      enabled: true
      path: /h2-console
      datasource:
          driver-class-name: org.h2.Driver
          url: ${DB_H2_URL}
          username: ${DB_H2_USERNAME}
          password: ${DB_H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
