spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_H2_URL}
    username: ${DB_H2_USERNAME}
    password: ${DB_H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
