spring:
  profiles:
    group:
      dev:
        - env
        - h2
      prod:
        - env
        - mysql
    default: dev

server:
  port: 8080

jwt:
  authorities-key: ${JWT_AUTHORITIES_KEY}
  secret-key: ${JWT_SECRET_KEY}
  access-token-expires-in: 7200 # 2 * 60 * 60

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
