spring:
  profiles:
    default: dev

---

spring:
  profiles:
    group:
      dev:
        - common
        - development
      prod:
        - common
        - production

---

spring:
  config:
    activate:
      on-profile: common
server:
  port: 8080
jwt:
  authorities-key: auth
  secret-key: SmFzdGVyMjUtU3ByaW5nQm9vdC1TcHJpbmdTZWN1cml0eS1hdXRoLUpXVC1zZWNyZXQta2V5LUpXVC1zZWNyZXQta2V5
  access-token-expires-in: 7200 # 2 * 60 * 60

---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portrade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.85.53:3306/portrade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug